// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: proto/solana-net.proto

package solananet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmationLevel int32

const (
	ConfirmationLevel_PROCESSED ConfirmationLevel = 0
	ConfirmationLevel_CONFIRMED ConfirmationLevel = 1
	ConfirmationLevel_FINALIZED ConfirmationLevel = 2
)

// Enum value maps for ConfirmationLevel.
var (
	ConfirmationLevel_name = map[int32]string{
		0: "PROCESSED",
		1: "CONFIRMED",
		2: "FINALIZED",
	}
	ConfirmationLevel_value = map[string]int32{
		"PROCESSED": 0,
		"CONFIRMED": 1,
		"FINALIZED": 2,
	}
)

func (x ConfirmationLevel) Enum() *ConfirmationLevel {
	p := new(ConfirmationLevel)
	*p = x
	return p
}

func (x ConfirmationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_solana_net_proto_enumTypes[0].Descriptor()
}

func (ConfirmationLevel) Type() protoreflect.EnumType {
	return &file_proto_solana_net_proto_enumTypes[0]
}

func (x ConfirmationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationLevel.Descriptor instead.
func (ConfirmationLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_solana_net_proto_rawDescGZIP(), []int{0}
}

type SendBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx                [][]byte          `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
	ConfirmationLevel ConfirmationLevel `protobuf:"varint,2,opt,name=confirmation_level,json=confirmationLevel,proto3,enum=solananet.ConfirmationLevel" json:"confirmation_level,omitempty"`
}

func (x *SendBatchRequest) Reset() {
	*x = SendBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_solana_net_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchRequest) ProtoMessage() {}

func (x *SendBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_solana_net_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchRequest.ProtoReflect.Descriptor instead.
func (*SendBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_solana_net_proto_rawDescGZIP(), []int{0}
}

func (x *SendBatchRequest) GetTx() [][]byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *SendBatchRequest) GetConfirmationLevel() ConfirmationLevel {
	if x != nil {
		return x.ConfirmationLevel
	}
	return ConfirmationLevel_PROCESSED
}

type SendBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature [][]byte `protobuf:"bytes,1,rep,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SendBatchResponse) Reset() {
	*x = SendBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_solana_net_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchResponse) ProtoMessage() {}

func (x *SendBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_solana_net_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchResponse.ProtoReflect.Descriptor instead.
func (*SendBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_solana_net_proto_rawDescGZIP(), []int{1}
}

func (x *SendBatchResponse) GetSignature() [][]byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_solana_net_proto protoreflect.FileDescriptor

var file_proto_solana_net_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2d, 0x6e,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61,
	0x6e, 0x65, 0x74, 0x22, 0x6f, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x4b, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x6e, 0x65, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x31, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2a, 0x40, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0d, 0x0a, 0x09,
	0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x49,
	0x4e, 0x41, 0x4c, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x02, 0x32, 0x52, 0x0a, 0x09, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78,
	0x12, 0x1b, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6f, 0x6c, 0x6d,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x75, 0x73, 0x74, 0x2d, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61,
	0x6e, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_solana_net_proto_rawDescOnce sync.Once
	file_proto_solana_net_proto_rawDescData = file_proto_solana_net_proto_rawDesc
)

func file_proto_solana_net_proto_rawDescGZIP() []byte {
	file_proto_solana_net_proto_rawDescOnce.Do(func() {
		file_proto_solana_net_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_solana_net_proto_rawDescData)
	})
	return file_proto_solana_net_proto_rawDescData
}

var file_proto_solana_net_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_solana_net_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_solana_net_proto_goTypes = []interface{}{
	(ConfirmationLevel)(0),    // 0: solananet.ConfirmationLevel
	(*SendBatchRequest)(nil),  // 1: solananet.SendBatchRequest
	(*SendBatchResponse)(nil), // 2: solananet.SendBatchResponse
}
var file_proto_solana_net_proto_depIdxs = []int32{
	0, // 0: solananet.SendBatchRequest.confirmation_level:type_name -> solananet.ConfirmationLevel
	1, // 1: solananet.Broadcast.SendTx:input_type -> solananet.SendBatchRequest
	2, // 2: solananet.Broadcast.SendTx:output_type -> solananet.SendBatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_solana_net_proto_init() }
func file_proto_solana_net_proto_init() {
	if File_proto_solana_net_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_solana_net_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_solana_net_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_solana_net_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_solana_net_proto_goTypes,
		DependencyIndexes: file_proto_solana_net_proto_depIdxs,
		EnumInfos:         file_proto_solana_net_proto_enumTypes,
		MessageInfos:      file_proto_solana_net_proto_msgTypes,
	}.Build()
	File_proto_solana_net_proto = out.File
	file_proto_solana_net_proto_rawDesc = nil
	file_proto_solana_net_proto_goTypes = nil
	file_proto_solana_net_proto_depIdxs = nil
}
